# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 04:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('index', models.IntegerField()),
                ('info', models.CharField(max_length=256)),
                ('coverImage', models.CharField(blank=True, max_length=256)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '广告轮播图',
                'verbose_name_plural': '广告轮播图',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='书籍名称')),
                ('info', models.CharField(max_length=256, verbose_name='书籍简介')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('stauts', models.CharField(max_length=20, verbose_name='状态')),
                ('coverImage', models.CharField(max_length=256, verbose_name='书籍封面')),
                ('readNum', models.IntegerField(default=0, verbose_name='浏览量')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '小说书籍',
                'verbose_name_plural': '小说书籍',
            },
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book')),
            ],
            options={
                'verbose_name': '用户书架',
                'verbose_name_plural': '用户书架',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='分类名称')),
                ('info', models.CharField(blank=True, max_length=256, null=True, verbose_name='分类描述')),
                ('coverImage', models.CharField(blank=True, max_length=256, null=True, verbose_name='分类封面图')),
            ],
            options={
                'verbose_name': '小说分类',
                'verbose_name_plural': '小说分类',
            },
        ),
        migrations.CreateModel(
            name='Chpater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='章节名称')),
                ('size', models.IntegerField(verbose_name='字数')),
                ('type', models.IntegerField(choices=[(1, '限免'), (2, 'VIP')], default=1, verbose_name='是否是VIP章节')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('readNum', models.IntegerField(default=0, verbose_name='浏览量')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '小说章节',
                'verbose_name_plural': '小说章节',
            },
        ),
        migrations.CreateModel(
            name='RecommendCetagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Category')),
            ],
            options={
                'verbose_name': '推荐分类',
                'verbose_name_plural': '推荐分类',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '用户token',
                'verbose_name_plural': '用户token',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=11, unique=True, verbose_name='账户')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('usertype', models.IntegerField(choices=[(1, '普通用户'), (2, 'VIP')], default=1, verbose_name='用户类型')),
                ('birthday', models.DateTimeField(default=datetime.datetime.now, verbose_name='出生年月')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='bookstore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='user.Category', verbose_name='所属分类'),
        ),
        migrations.AlterUniqueTogether(
            name='bookstore',
            unique_together=set([('book', 'user')]),
        ),
    ]
