# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bookstore'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookstore',
            unique_together=set([('book', 'user')]),
        ),
    ]
